spring:
  application:
    name: Crypto

  server:
    port: 8080

  data:
    mongodb:
      uri: mongodb://localhost:27017/crypto_db
    profiles:
      active: dev

jwt:
  secret: aaa336942514336942514aaa33694251412

app:
  symbols:
    - BTCUSDT
    - ETHUSDT
  base-url: https://api.binance.com
  update-interval: 3

alerts:
  default-threshold: 5.0
  thresholds:
    BTCUSDT: 0.01
    ETHUSDT: 0.01