spring:
  application:
    name: Crypto

  data:
    mongodb:
      uri: mongodb://localhost:27017/crypto_db
    profiles:
      active: dev

jwt:
  secret: aaa336942514336942514aaa33694251412

app:
  symbols:
    - BTCUSDT
    - ETHUSDT
  base-url: https://api.binance.com
  update-interval: 3
